CREATE DATABASE TRAINING_DB;

USE TRAINING_DB;

-- 1. Students
CREATE TABLE STUDENTS (
    S_ID INT PRIMARY KEY AUTO_INCREMENT,
    S_NAME VARCHAR(20) NOT NULL,
    S_PHONE VARCHAR(10) UNIQUE NOT NULL,
    S_EMAIL VARCHAR(50) UNIQUE NOT NULL,
    S_AGE INT CHECK (S_AGE >= 18)
);

-- 2. Trainers
CREATE TABLE TRAINERS (
    T_ID INT PRIMARY KEY AUTO_INCREMENT,
    T_NAME VARCHAR(20) NOT NULL
);

-- 3. Courses
CREATE TABLE COURSES (
    C_ID INT PRIMARY KEY AUTO_INCREMENT,
    C_NAME VARCHAR(20) UNIQUE NOT NULL,
    C_FEE INT DEFAULT 15000 NOT NULL,
    C_T_ID INT NOT NULL,

    CONSTRAINT T_DETAILS
        FOREIGN KEY (C_T_ID)
        REFERENCES TRAINERS(T_ID)
);

-- 4. Enrollments
CREATE TABLE ENROLLMENTS (
    E_ID INT PRIMARY KEY AUTO_INCREMENT,
    E_S_ID INT NOT NULL,
    E_C_ID INT NOT NULL,
    E_T_ID INT NOT NULL,
    E_DATE DATE DEFAULT (CURRENT_DATE),

    CONSTRAINT S_DETAILS
        FOREIGN KEY (E_S_ID)
        REFERENCES STUDENTS(S_ID),

    CONSTRAINT C_DETAILS
        FOREIGN KEY (E_C_ID)
        REFERENCES COURSES(C_ID),

    CONSTRAINT E_T_DETAILS
        FOREIGN KEY (E_T_ID)
        REFERENCES TRAINERS(T_ID)
);
SELECT *FROM STUDENTS;
SELECT * FROM COURSES;
SELECT * FROM ENROLLMENTS;
